### ISSUE TITLE
Flint blog post

### ISSUE THREAD

**Issue by jonathancstroud** [MichiganDataScienceTeam/MichiganDataScienceTeam.github.io#10]
Add a blog post about the current state of the Flint project.

Make sure to mention:
- The Google grant
- The group field trip
- Some initial findings with charts/interactive maps

**Comment by the-alex** [comment]
I'm thinking we can have a generic, 'this is what we have done so far' section with news about the Google grant and the group field trip, and then spotlight two key findings with commentary from people who worked on those findings within MDST. The more interactive stuff, the better. Sound good?

My current plan is to have a near-perfect draft done a week from now. Can you edit/review stuff if I ask you to? There will be a remote branch you can checkout.
