### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by jonathancstroud** [MichiganDataScienceTeam/MichiganDataScienceTeam.github.io#13]
Embed MSAIL google calendar as on the old website.

**Comment by the-alex** [comment]
We should use [fullcalendar.js](http://fullcalendar.io/) for this. The [C4CS website](c4cs.github.io) used it and it looks pretty nice.

**Comment by the-alex** [comment]
[Or just embed the calendar normally](https://support.google.com/calendar/answer/41207?hl=en) ... Yeah, this first.
