### ISSUE TITLE
Updated team photo and member list

### ISSUE THREAD

**Issue by jonathancstroud** [MichiganDataScienceTeam/MichiganDataScienceTeam.github.io#14]
Update the cover photo found on the "about us" page to something more recent.

Also include a list of current active members with brief bios

**Comment by the-alex** [comment]
> Update the cover photo found on the "about us" page to something more recent.

I would, but I actually don't think we have a good photo of 'everyone'. We have the Flint Water Plan Photo, but the sky was pretty dreary that day. If I were still there, I'd take my camera out to the meeting and have everyone line up at the fountain behind Cooley on a nice day.

> Also include a list of current active members with brief bios

It's really difficult to keep an active member list. When does someone become 'inactive'? We could outsource this concern by letting people write it themselves and make a PR with the code. Or we could just do bios for the Test Set?
